### ISSUE TITLE
authenticate

### ISSUE THREAD

**Issue by Moh-an** [akverma26/Voting-System-using-Block-Chain-Technology#2]
how to aadhar authenticate

**Comment by thisiskapil** [comment]
Yep , I am stuck in this too.
@akverma26

**Comment by shivi0708** [comment]
Can you please tell @akverma26 how to authenticate through Aadhar? It is repeatedly showing invalid AAdhar number.

**Comment by BalajiGunasekaran1** [comment]
change aadhar_no = request.GET.get('aadhar_no') to  aadhar_no = request.POST.get('aadhar_no') in home/view.py (line 33)

**Comment by yourabhi** [comment]
Hi it is still not working do we need to put our original adhaar card number

**Comment by akverma26** [comment]
We are not using original aadhar numbers here, instead we are playing with some dummy data.

Check dummy data section `https://vote.pythonanywhere.com/create-dummy-data/` page, you'll get the idea.

For ref following dummy aadhar numbers are generated that you can use for authentication and further demonstration. Or you can check more info by running this project locally and login to admin page

```

123456789010
123456789009
123456789008
123456789007
123456789006
123456789005
123456789004
123456789003
123456789002
123456789001
```
