### ISSUE TITLE
access

### ISSUE THREAD

**Issue by nishiltejani** [akverma26/Voting-System-using-Block-Chain-Technology#5]
you wrote that "to access this page you need to deploy your own version or run it locally."

so how to deploy my own version or run it locally.

**Comment by Lokesh04** [comment]
Hi @nishiltejani
follow steps
step 1:
`git clone https://github.com/akverma26/Voting-System-using-Block-Chain-Technology.git voting-system
`
step 2: 
```
go/to/project_directory

e.g ~/Desktop/project/voting-system

```
step 3:
`pip3 install -r requirements.txt
`

step 4: 
`python3 manage.py runserver
`

if you get any error msg or warnings like 
```
You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth.
Run 'python manage.py migrate' to apply them.

```
then 
step 5:
`python3 manage.py migrate `
